name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make PugiXMLTarget CC=g++ 
    - name: make
      run: make LibAvoidTarget CC=g++
    - name: make
      run: make IDEFPlotTarget CC=g++
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: runcommand
      run: ./a.out TestData.xml Diagram.txt 400 300 32 6 10 10
