name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Compile pugi
      run: make PugiXMLTarget CC=g++ 
    - name: Compile lib avoid
      run: make LibAvoidTarget CC=g++
    - name: Compile IDEFPlot target
      run: make IDEFPlotTarget CC=g++
    - name: Upload build output
      uses: actions/upload-artifact@v3
      with:
        name: idefplot-binary
        path: a.out
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download the binary artifact
      uses: actions/download-artifact@v3
      with:
        name: idefplot-binary
    - name: Enable binary execution
      run: chmod +x a.out
    - name: Run IDEFPlot
      run: ./a.out TestData.xml Diagram.txt 400 300 32 6 10 10
    - name: Upload diagram
      uses: actions/upload-artifact@v3
      with:
        name: test-diagram
        path: Diagram.txt
